FROM python

RUN apt-get update && apt-get -y install python3-pip && \
 pip3 install python-dateutil psycopg2 sqlalchemy numpy matplotlib xmltodict \
 geopy json-logging nats-python

RUN mkdir -p /opt/points
COPY ./ /opt/points
WORKDIR /opt/points
RUN python setup.py install
