FROM python

RUN apt-get update
RUN apt-get -y install python3-pip
RUN pip3 install python-dateutil
RUN pip3 install psycopg2
RUN pip3 install sqlalchemy
RUN mkdir -p /opt/points
COPY ./ /opt/points
WORKDIR /opt/points
RUN python setup.py install
